function user_confirm_excel_file
    f = figure('Units','Normalized',...
        'Position',[.4 .4 .3 .3],...
        'NumberTitle','off',...
        'Name','Info');
    set(gcf,'Color',[0.6,0.3,0.8])

    p1= uicontrol('Style','PushButton',...
        'Units','Normalized',...
        'Position',[.4 .6 .2 .1],...
        'String','Done',...
        'CallBack','uiresume(gcbf)');
    p2= uicontrol('Style','text',...
        'Units','Normalized',...
        'Position',[.35 .2 .3 .3],...
        'String','Give corrected MFR with T_TD in the MFR_data.xls file (In A column give T_TD (in oC) and in B column give MFR) ',...
        'CallBack','uiresume(gcbf)');
    uiwait(f)
    close(f)